Starting Container

[2024-12-26 13:13:15 +0000] [1] [INFO] Starting gunicorn 20.1.0

[2024-12-26 13:13:15 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)

[2024-12-26 13:13:15 +0000] [1] [INFO] Using worker: sync

[2024-12-26 13:13:15 +0000] [4] [INFO] Booting worker with pid: 4

Configurando PostgreSQL: postgresql://postgres:xlyrMBRFPdTjeMRtzxJyDIlQEwNPIDfJ@postgres.railway.internal:5432/railway

[2024-12-26 13:13:52,969] ERROR in app: Exception on /api/recent-records [GET]

Traceback (most recent call last):

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context

    self.dialect.do_execute(

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute

    cursor.execute(statement, parameters)

psycopg2.errors.UndefinedTable: relation "record" does not exist

LINE 2: FROM record JOIN vehicle ON vehicle.id = record.vehicle_id O...

             ^

 

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2070, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1515, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1513, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1499, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/app.py", line 165, in get_recent_records

    records = db.session.query(Record, Vehicle).join(Vehicle).order_by(Record.timestamp.desc()).limit(10).all()

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2711, in all

    return self._iter().all()

           ^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter

    result = self.session.execute(

             ^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1689, in execute

    result = conn._execute_20(statement, params or {}, execution_options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
